POOL_ADDRESS_PROVIDER_ADDRESS = "0xf3Ba4D1b50f78301BDD7EAEa9B67822A15FCA691"
POOL_ADDRESS_PROVIDER_ABI = address_provider_abi = [
    {"inputs": [{"internalType": "string", "name": "marketId", "type": "string"},
             {"internalType": "address", "name": "owner", "type": "address"}], "stateMutability": "nonpayable",
  "type": "constructor"}, {"anonymous": False, "inputs": [
    {"indexed": True, "internalType": "address", "name": "oldAddress", "type": "address"},
    {"indexed": True, "internalType": "address", "name": "newAddress", "type": "address"}], "name": "ACLAdminUpdated",
                           "type": "event"}, {"anonymous": False, "inputs": [
    {"indexed": True, "internalType": "address", "name": "oldAddress", "type": "address"},
    {"indexed": True, "internalType": "address", "name": "newAddress", "type": "address"}], "name": "ACLManagerUpdated",
                                              "type": "event"}, {"anonymous": False, "inputs": [
    {"indexed": True, "internalType": "bytes32", "name": "id", "type": "bytes32"},
    {"indexed": True, "internalType": "address", "name": "oldAddress", "type": "address"},
    {"indexed": True, "internalType": "address", "name": "newAddress", "type": "address"}], "name": "AddressSet",
                                                                 "type": "event"}, {"anonymous": False, "inputs": [
    {"indexed": True, "internalType": "bytes32", "name": "id", "type": "bytes32"},
    {"indexed": True, "internalType": "address", "name": "proxyAddress", "type": "address"},
    {"indexed": False, "internalType": "address", "name": "oldImplementationAddress", "type": "address"},
    {"indexed": True, "internalType": "address", "name": "newImplementationAddress", "type": "address"}],
                                                                                    "name": "AddressSetAsProxy",
                                                                                    "type": "event"},
 {"anonymous": False, "inputs": [{"indexed": True, "internalType": "string", "name": "oldMarketId", "type": "string"},
                                 {"indexed": True, "internalType": "string", "name": "newMarketId", "type": "string"}],
  "name": "MarketIdSet", "type": "event"}, {"anonymous": False, "inputs": [
    {"indexed": True, "internalType": "address", "name": "previousOwner", "type": "address"},
    {"indexed": True, "internalType": "address", "name": "newOwner", "type": "address"}],
                                            "name": "OwnershipTransferred", "type": "event"}, {"anonymous": False,
                                                                                               "inputs": [
                                                                                                   {"indexed": True,
                                                                                                    "internalType": "address",
                                                                                                    "name": "oldAddress",
                                                                                                    "type": "address"},
                                                                                                   {"indexed": True,
                                                                                                    "internalType": "address",
                                                                                                    "name": "newAddress",
                                                                                                    "type": "address"}],
                                                                                               "name": "PoolConfiguratorUpdated",
                                                                                               "type": "event"},
 {"anonymous": False, "inputs": [{"indexed": True, "internalType": "address", "name": "oldAddress", "type": "address"},
                                 {"indexed": True, "internalType": "address", "name": "newAddress", "type": "address"}],
  "name": "PoolDataProviderUpdated", "type": "event"}, {"anonymous": False, "inputs": [
    {"indexed": True, "internalType": "address", "name": "oldAddress", "type": "address"},
    {"indexed": True, "internalType": "address", "name": "newAddress", "type": "address"}], "name": "PoolUpdated",
                                                        "type": "event"}, {"anonymous": False, "inputs": [
    {"indexed": True, "internalType": "address", "name": "oldAddress", "type": "address"},
    {"indexed": True, "internalType": "address", "name": "newAddress", "type": "address"}],
                                                                           "name": "PriceOracleSentinelUpdated",
                                                                           "type": "event"}, {"anonymous": False,
                                                                                              "inputs": [
                                                                                                  {"indexed": True,
                                                                                                   "internalType": "address",
                                                                                                   "name": "oldAddress",
                                                                                                   "type": "address"},
                                                                                                  {"indexed": True,
                                                                                                   "internalType": "address",
                                                                                                   "name": "newAddress",
                                                                                                   "type": "address"}],
                                                                                              "name": "PriceOracleUpdated",
                                                                                              "type": "event"},
 {"anonymous": False, "inputs": [{"indexed": True, "internalType": "bytes32", "name": "id", "type": "bytes32"},
                                 {"indexed": True, "internalType": "address", "name": "proxyAddress",
                                  "type": "address"},
                                 {"indexed": True, "internalType": "address", "name": "implementationAddress",
                                  "type": "address"}], "name": "ProxyCreated", "type": "event"},
 {"inputs": [], "name": "getACLAdmin", "outputs": [{"internalType": "address", "name": "", "type": "address"}],
  "stateMutability": "view", "type": "function"},
 {"inputs": [], "name": "getACLManager", "outputs": [{"internalType": "address", "name": "", "type": "address"}],
  "stateMutability": "view", "type": "function"},
 {"inputs": [{"internalType": "bytes32", "name": "id", "type": "bytes32"}], "name": "getAddress",
  "outputs": [{"internalType": "address", "name": "", "type": "address"}], "stateMutability": "view",
  "type": "function"},
 {"inputs": [], "name": "getMarketId", "outputs": [{"internalType": "string", "name": "", "type": "string"}],
  "stateMutability": "view", "type": "function"},
 {"inputs": [], "name": "getPool", "outputs": [{"internalType": "address", "name": "", "type": "address"}],
  "stateMutability": "view", "type": "function"},
 {"inputs": [], "name": "getPoolConfigurator", "outputs": [{"internalType": "address", "name": "", "type": "address"}],
  "stateMutability": "view", "type": "function"},
 {"inputs": [], "name": "getPoolDataProvider", "outputs": [{"internalType": "address", "name": "", "type": "address"}],
  "stateMutability": "view", "type": "function"},
 {"inputs": [], "name": "getPriceOracle", "outputs": [{"internalType": "address", "name": "", "type": "address"}],
  "stateMutability": "view", "type": "function"}, {"inputs": [], "name": "getPriceOracleSentinel", "outputs": [
    {"internalType": "address", "name": "", "type": "address"}], "stateMutability": "view", "type": "function"},
 {"inputs": [], "name": "owner", "outputs": [{"internalType": "address", "name": "", "type": "address"}],
  "stateMutability": "view", "type": "function"},
 {"inputs": [], "name": "renounceOwnership", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
 {"inputs": [{"internalType": "address", "name": "newAclAdmin", "type": "address"}], "name": "setACLAdmin",
  "outputs": [], "stateMutability": "nonpayable", "type": "function"},
 {"inputs": [{"internalType": "address", "name": "newAclManager", "type": "address"}], "name": "setACLManager",
  "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {
     "inputs": [{"internalType": "bytes32", "name": "id", "type": "bytes32"},
                {"internalType": "address", "name": "newAddress", "type": "address"}], "name": "setAddress",
     "outputs": [], "stateMutability": "nonpayable", "type": "function"}, {
     "inputs": [{"internalType": "bytes32", "name": "id", "type": "bytes32"},
                {"internalType": "address", "name": "newImplementationAddress", "type": "address"}],
     "name": "setAddressAsProxy", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
 {"inputs": [{"internalType": "string", "name": "newMarketId", "type": "string"}], "name": "setMarketId", "outputs": [],
  "stateMutability": "nonpayable", "type": "function"},
 {"inputs": [{"internalType": "address", "name": "newPoolConfiguratorImpl", "type": "address"}],
  "name": "setPoolConfiguratorImpl", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
 {"inputs": [{"internalType": "address", "name": "newDataProvider", "type": "address"}], "name": "setPoolDataProvider",
  "outputs": [], "stateMutability": "nonpayable", "type": "function"},
 {"inputs": [{"internalType": "address", "name": "newPoolImpl", "type": "address"}], "name": "setPoolImpl",
  "outputs": [], "stateMutability": "nonpayable", "type": "function"},
 {"inputs": [{"internalType": "address", "name": "newPriceOracle", "type": "address"}], "name": "setPriceOracle",
  "outputs": [], "stateMutability": "nonpayable", "type": "function"},
 {"inputs": [{"internalType": "address", "name": "newPriceOracleSentinel", "type": "address"}],
  "name": "setPriceOracleSentinel", "outputs": [], "stateMutability": "nonpayable", "type": "function"},
 {"inputs": [{"internalType": "address", "name": "newOwner", "type": "address"}], "name": "transferOwnership",
  "outputs": [], "stateMutability": "nonpayable", "type": "function"}]
